apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: todo-api
      app.kubernetes.io/part-of: todo
    includeSelectors: true
    includeTemplates: true
images:
  - name: docker.io/shatri/todo-api-node
    newTag: v1
